---
name: release

on:
  release:
    types: [prereleased, released]

env:
  PIP_CACHE_DIR: ~/.cache/pip
  PY_VERSION: 3.8
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ASSET_NAME: skeleton-aws-lambda_${{ env.PY_VERSION }}.zip
    steps:
      - uses: actions/checkout@v2
      - id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Cache lambda building environments
        uses: actions/cache@v2
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: "release-${{ runner.os }}-\
            py${{ steps.setup-python.outputs.python-version }}-\
            ${{ hashFiles('**/requirements.txt') }}"
          restore-keys: |
            release-${{ runner.os }}-\
            py${{ steps.setup-python.outputs.python-version }}-
            release-${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install --upgrade --requirement requirements.txt
      - name: Build environment
        run: docker-compose build --build-arg PY_VERSION=${{ env.PY_VERSION }}
      - name: Generate lambda zip
        run: docker-compose up
      - name: Upload lambda zip as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/zip
