---
name: release

on:
  release:
    types: [prereleased, released]

env:
  PIP_CACHE_DIR: ~/.cache/pip
  PY_VERSION: 3.8
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ASSET_NAME: ${{ github.event.repository.name }}.zip
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: "docker-compose build \
          --build-arg PY_VERSION=${{ env.PY_VERSION }} \
          --build-arg FILE_NAME=${{ github.event.repository.name }} \
          --build-arg IS_RELEASE=TRUE"
      - name: Generate lambda zip
        run: docker-compose up
      - name: Upload lambda zip as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ASSET_NAME }}
          asset_name: ${{ env.ASSET_NAME }}
          asset_content_type: application/zip
